import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar';

const inter = Inter({ subsets: ['latin'] })






export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
          </Head>

          <main className={styles.main}>
              <Navbar></Navbar>

              <div className={styles.description}>
               
          <p>
            Nav bar here        
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}

            </a>
          </div>
        </div>

        <div className={styles.center}>
         <p>
          Discover Local Produce
        </p>
         <p>
          Get our newsletter to be informed on fresh, local produce.
         </p>
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
          <div>
            <img src="/images/Fruit.png" alt=""/>
            </div>
            <h2 className={inter.className}>
              Fruit <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Find fruit sellers in your neighborhood
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
               <div>
            <img src="/images/Veggies.png" alt=""/>
            </div>
            <h2 className={inter.className}>
              Veggies <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Find veggie sellers in your neighborhood
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
               <div>
            <img src="/images/Nuts.png" alt=""/>
            </div>
            <h2 className={inter.className}>
             Nuts <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Find nut sellers in your neighborhood
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
               <div>
            <img src="/images/Honey.png" alt=""/>
            </div>
            <h2 className={inter.className}>
              Honey <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
            Find honey sellers in your neighborhood
            </p>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
               <div>
            <img src="/images/Eggs.png" alt=""/>
            </div>
            <h2 className={inter.className}>
              Eggs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find egg sellers in your neighborhood
              
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
